### ISSUE TITLE
add .gitignore to the archive

### ISSUE THREAD

**Issue by musketyr** [bmuschko/gradle-initializr#1]
it would be great if the downloaded archive contains default `.gitignore` file. `.editorconfig` would be also great.

**Comment by bmuschko** [comment]
That's a good idea. At the moment Gradle Initializr just calls off to the Gradle's init task and bundles whatever it creates into an archive. Wondering where the logic to create the files should live. I feel like it would probably be best if those files would be created by the `init` task in Gradle core. I am not opposed to building it into Gradle Initializr though. Would you be interested in providing a pull request?

**Comment by musketyr** [comment]
If you can point me to some direction, where to start

**Comment by bmuschko** [comment]
I'd probably add the logic here: https://github.com/bmuschko/gradle-initializr/blob/master/src/main/java/com/bmuschko/gradle/initializr/service/DefaultGradleInitializrService.java#L44

**Comment by musketyr** [comment]
Well it should be as simple as copy a file into the temporary folder. 

https://docs.oracle.com/javase/7/docs/api/java/nio/file/Files.html#copy(java.io.InputStream,%20java.nio.file.Path,%20java.nio.file.CopyOption...)

**Comment by bmuschko** [comment]
The files you want don't really exist so you'd need to create them and then bundled them as part of the archive. Furthermore, the tests would have to verify the existence and expected content of those files.

**Comment by bmuschko** [comment]
This has been fixed: https://github.com/bmuschko/gradle-initializr/commit/939c94559f7048bf6e3fa1753eee922ce7bcfb30
