### ISSUE TITLE
Feature wanted: support android project?

### ISSUE THREAD

**Issue by walfud** [bmuschko/gradle-initializr#3]

**Comment by bmuschko** [comment]
Currently this project only calls the Gradle `init` task to generate new projects. The `init` task doesn't support Android projects yet. I think it would be best if you open an issue at [gradle/gradle](https://github.com/gradle/gradle). Once its available its very easily to use it from here.

**Comment by walfud** [comment]
> Currently this project only calls the Gradle `init` task to generate new projects. The `init` task doesn't support Android projects yet. I think it would be best if you open an issue at [gradle/gradle](https://github.com/gradle/gradle). Once its available its very easily to use it from here.

ok
