### ISSUE TITLE
Failed to connect to repository

### ISSUE THREAD

**Issue by sumitsethi2k** [bmuschko/gradle-initializr#7]
Trying to integrate this in Jenkins through GIT and getting the following error:
Failed to connect to repository : Error performing git command: git ls-remote -h git@github.com:bmuschko/gradle-initializr.git HEAD

![GIT](https://user-images.githubusercontent.com/51478885/100675664-5d151480-338d-11eb-972d-8c352152f199.JPG)

**Comment by bmuschko** [comment]
It's very likely an issue with your local Git installation. I'd also try to use the HTTPS URL instead: https://github.com/bmuschko/gradle-initializr.git
